### ISSUE TITLE
Wrong PHPUnit version for PHP 7.2, should be PHPUnit 8, not 9

### ISSUE THREAD

**Issue by ptyskju** [ambroisemaupate/docker#3]
Thank you for useful docker image!
In **php72-runner** there is wrong PHPUnit version, should be 8, not latest.

Instead of  
https://github.com/ambroisemaupate/docker/blob/38e2634f56b09b0b03681164ae02010767169aeb/php72-runner/Dockerfile#L126

should be 
```Dockerfile
 RUN curl -sSLo phpunit.phar https://phar.phpunit.de/phpunit-8.phar \
```

**Comment by ambroisemaupate** [comment]
New image will be available in docker hub in several hours.

Thanks for your suggestion.
